### ISSUE TITLE
Double suffix under certain conditions

### ISSUE THREAD

**Issue by fuzzything44** [erosson/swarm-numberformat#20]
I haven't really done much testing to isolate the issue, but `numberformat.formatShort(999999, { sigfigs: 3 });` returns the string "1.00e+3K". (I'm formatting 1M - 1, getting I guess a million just written very strangely)

**Comment by erosson** [comment]
Should be fixed in the next release (0.4.0). The prefix was rounding up into a form that created a second prefix. It should now always round down, so 999999 is "999K".

Thanks for reporting this!
