### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by TotomInc** [erosson/swarm-numberformat#21]
Would be sooo great to have typings for Typescript. You could use [dts-gen](https://github.com/Microsoft/dts-gen) and publish it under `@types/swarm-numberformat`. :)

**Comment by erosson** [comment]
I've never used Typescript, so I'm afraid this will not be a high priority for me. Happy to accept outside contributions, though!

**Comment by TotomInc** [comment]
I'll see what I can do!

**Comment by TotomInc** [comment]
So, I started to work on the typings, and after looking more at the docs it looks like there some major options missing. The `Parser` class is not well documented, as well some methods like `format`, `parse`, `requiredDecimal`, ...
